service: concept-api

plugins:
  - serverless-plugin-typescript
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10
  profile: Jose
  stage: prod
  region: us-east-1
  environment: # add environment property
    NODE_ENV: PROD

# you can add packaging information here
package:
  exclude:
  include:
    - src/**/*

functions:
  main:
    handler: src/handler.main
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{any+}
          method: ANY
